version: "3.7"

services:
  nano-work-server:
    build: ./nano-work-server
    image: nano-work-server
    command: -c 4 -l 0.0.0.0:7000
    
  boompow-client:
    build: ./boompow-client
    image: boompow-client
    command: --limit-logging --async_mode --payout ban_3f53c3ropjec1yrfimp6ic3fdjn6mqaid9ctsp6678z8f9kweqksux8xykpm --worker_uri nano-work-server:7000
    
  dpow-client:
    build: ./dpow-client
    image: dpow-client
    depends_on:
      - nano-work-server
    command: --payout nano_3x5iwddhm3cdcegeyrbftcfayyee6bj71z48i3f5e8ajjd14e43hr71oc86y --worker_uri nano-work-server:7000
